version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

  backend:
    build: 
      context: ./formhub-be
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 5000:5000
      - 9229:9229 # debugger port
    volumes:
      - ./formhub-be:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 5000
      REDIS_HOST: redis

  frontend:
    build:
      context: ./formhub-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./formhub-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:5000

volumes:
  postgres-data: